<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>SR1SlimesOnly</AssemblyName>
    <RootNamespace>SR1SlimesOnly</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(MelonLoaderDir)/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>